### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bosd** [monero-integrations/moneroodoo#13]
Roadmap / todo:
- [ ] auto Create XMR journal
- [ ] Base xmr bookkeeping
- [ ] add payment list like in [monerowp](https://github.com/monero-integrations/monerowp/blob/master/include/admin/class-monero-admin-payments-list.php)
- [ ] qr code on receipts / invoices
- [ ] Documentation how to use in dockerized environment.
- [ ] Add /document tier based confirmations
